Remove npm.js gitignore
dusk-network/dusk-wallet-js pull request #48
Opened 2024-01-24 13:40 UTC by Daksh14

2024-01-24 13:58 UTC, ZER0 requested changes
See the comment.
The tool / task requires more work that the code you used locally, because we *need* to create a coupling between the versioning of the node package and the tags of the repo; as mentioned yesterday.

That means that most likely you need to use a `semver` package for that, at least – you don't need a git one, most likely you should be able to execute everything by spawn a process and call `git` there. Of course, if `git` is not installed, you throw an error.

2024-01-24 13:58 UTC, ZER0 commented on npm.js
> +    version: Deno.args[0],
The idea here is the following:

1. If no version is given from the command line, it uses the most recent (in terms of semver) tag that is present. If no valid tags exists, throws an error.

2. If a version is given from the command line, it checks if it exists in the tags present in the repo. If not, throws an error.

In both cases, if the operation succeed, the tool needs to temporary checkout the code at the valid tag given or found, build the library, and then check back the initial starting commit.

If the repo is "dirty" – there are changes that are not committed – the tool should throw an error.

2024-02-13 22:10 UTC, ZER0 requested changes
I did the review commit after commit, however as mentioned previously for long living branch – that shouldn't exists to begin with, but sometimes this kind of things happen –we should branch out, having atomic commits that we will going to merge into the long living branch, and then to the default branch.
Here the changes are without atomic scope, there are not explained nor discussed, and therefore is basically impossible to follow the line of thoughts.

2024-02-13 22:10 UTC, ZER0 commented on .github/workflows/test.yaml
> +        WALLET_CORE_PATH: "./assets/dusk_wallet_core.wasm"
The name is wrong, it should contains the version. Not sure why the asset now is stripped by the versioning.
Why you changed what I did yesterday without consulting? I thought I explain why it's needed. Please, rename it in `dusk_wallet_core@0.21.9-rc.wasm`, that was the name we had yesterday.

2024-02-13 22:10 UTC, ZER0 commented on src/node.js
> +
That's _very_ bad: never do this, never modify the prototype of classes / objects you don't own: it's like the orphan rules of Rust we have to apply manually to JS.

Also, you can just use `concat` or the spread syntax.

2024-02-13 22:10 UTC, ZER0 commented on src/node.js
> +  const blockHeights = owned.block_heights.split(",").map(Number);
I think block_heights should be a `u64` so `Number` is not suitable.

2024-02-13 22:10 UTC, ZER0 commented on tests/balance_test.js
> +    assertEquals(psks.length, 4);
I thought I said we should have 2 keys: any reason to use 4?

2024-02-13 22:10 UTC, ZER0 commented on assets/dusk_wallet_core.wasm
Please, rename it as it was yesterday.

2024-02-13 22:10 UTC, ZER0 commented on src/node.js
> +  const startTime = performance.now();
I don't think those should be in production. It's probably a leftover from your testing. Please remove them.

2024-02-13 22:10 UTC, ZER0 commented on src/node.js
> +    let chunkSize = 632;
Where this number comes from? Also, it looks more like constant rather than a variable.

Why this changes was needed anyway? It doesn't looks like it's part of this PR and it's not documented anywhere.

2024-02-13 22:10 UTC, ZER0 commented on src/node.js
> +  }
See above.

2024-02-13 22:10 UTC, ZER0 commented on src/node.js
> +
This looks like debug statements, the shouldn't be here.

2024-02-13 22:10 UTC, ZER0 commented on tests/npm_build_test.js
> +
This is wrong. Why are you fetching during a unit test? This might lead to several undesirable side effects.
Also, it's not documented anywhere *why* this is needed.

2024-02-14 07:43 UTC, Daksh14 commented on tests/npm_build_test.js
> +
The CI wasn't passing without this, it was giving a pathspec - not found error. This fixed it

2024-02-14 07:43 UTC, Daksh14 commented on src/node.js
> +  }
This change came from wrongly merged branch, It should be reverted

2024-02-14 07:44 UTC, Daksh14 commented on tests/balance_test.js
> +    assertEquals(psks.length, 4);
I kept it 4 because it won't be a significant difference between 2, I can change it to 2 if you want

2024-02-14 11:20 UTC, ZER0 commented on tests/npm_build_test.js
> +
Yeah, but:
a) Why it fixes it?
b) Where is the documentation about why it fixes it?
c) Have you considered what is the implication of doing so…?

2024-02-14 11:22 UTC, ZER0 commented on src/node.js
> +  }
Perfect. As mentioned, since everything was merged in the same PR, I could only go commit by commit. So it's possible that a later commit reverted it. Please, as noted, in the future if we have a long living branch, do a separate branch to merge into it (but let's try to avoid long living branch to begin with…)

2024-02-14 15:40 UTC, ZER0 approved these changes

2024-02-14 15:45 UTC, merged