Apply the address refactor
dusk-network/dusk-wallet-js pull request #74
Opened 2024-02-27 09:36 UTC by Daksh14

Closes #71

2024-03-05 07:09 UTC, ZER0 requested changes
Few nits here and there. But most importantly, I'm not sure we want to land this change yet. While I believe we should release the library version with `Gas` class, because it also fixes a bug, adding `Address` is just ergonomics, but requires several changes across the code base for the web wallet. In addition, the class was made in prevision of multiple addresses, but we're not going to use, for the time being, more than the default address on the web wallet. So I'm afraid is just going to add complexity.

Let's maybe discuss it.

2024-03-05 07:09 UTC, ZER0 commented on src/contracts/stake.js
> +    refund: refund.toString(),
You can revert this change, here, since `Address` is a subclass of `String`. You don't need to call explicitly `toString()`.
This comment is applied to all occurrences you will have in this PR.

2024-03-05 07:09 UTC, ZER0 commented on src/contracts/stake.js
> +    sender_index: senderIndex,
I would suggest to call the local variables here with the same naming convention of the arguments' name, so you can use the shortcut (this is apply to the whole project BTW):
```js
const args = {
  rng_seed: [...rng_seed],
  seed,
  refund,
  value,
  sender_index,
  gas_limit,
  gas_price,
};
```

2024-03-05 07:09 UTC, ZER0 commented on src/db.js
> +    (await db.cache.get(psk.toString())) ?? new HistoryData(psk, []);
Rename `psk` in the whole library when an `Address` is used.

2024-03-05 07:09 UTC, ZER0 commented on src/history.js
> +  const index = psk.index;
you can destruct instead:
```js
const { index } = psk;
```

Or, since we mentioned to rename `psk` into `address`:
```js
const { index } = address;
```

2024-03-05 07:09 UTC, ZER0 commented on src/history.js
> +    }),
It's a bit weird the usage of `map` here for this reason, but it's not in the scope of the PR, we can discuss later.

2024-03-05 07:09 UTC, ZER0 commented on src/mod.js
> +      this.#addresses = this.getPsks().then((addrs) =>
Internally it shouldn't use `getPsks()`.
We said that we want to keep `getPsks()` for the time being, at least for one version, so we can given time to check the usage of both, but if `addresses` uses internally `this.getPsks` then if we remove `this.getPsks` also `addresses` will stop to work. We need to be sure that the two are decupled.

2024-03-05 07:09 UTC, ZER0 commented on tests/balance_test.js
> +  async fn() {
This doesn't need to be `async` no?

2024-03-05 07:11 UTC, Daksh14 commented on src/contracts/stake.js
> +    refund: refund.toString(),
> You can revert this change, here, since `Address` is a subclass of `String`. You don't need to call explicitly `toString()`. This comment is applied to all occurrences you will have in this PR.

It wasn't working without .toString(), it returned `undefined` without it

2024-03-05 07:13 UTC, Daksh14 commented on tests/balance_test.js
> +  async fn() {
> This doesn't need to be `async` no?

`Wallet.addresses()` returns a Promise

2024-03-05 08:48 UTC, ZER0 commented on src/contracts/stake.js
> +    refund: refund.toString(),
Then there is a bug that needs to be fixed. The whole reason to extends from string was basically that. You can test yourself (in both browser and deno) a simple script like this:

```js
class Foo extends String {
  constructor(value) {
    super(value)
  }
}

let foo = new Foo("Baz");

let args = {
  bar: 10,
  foo,
}

console.log(JSON.stringify(args)) // '{"bar":10,"foo":"Baz"}'
```

When something does not work as it should, we need to find the reason before any workaround, because often can be a symptom of something wrong – or different from what we thought we coded.

2024-03-05 08:50 UTC, ZER0 commented on tests/balance_test.js
> +  async fn() {
Sure, but you're not "awaiting" anything here. You already "awaited" before.

2024-07-12 00:31 UTC, Daksh14 commented
Closed as implementation has changed

2024-07-12 00:31 UTC, closed without merging