Add getNetworkBlockHeight method
dusk-network/dusk-wallet-js pull request #79
Opened 2024-03-15 15:30 UTC by Daksh14

Fixes #75

2024-03-15 16:10 UTC, ZER0 requested changes

2024-03-15 16:10 UTC, ZER0 commented on CHANGELOG.md
> +- Add tests for the new `getNetworkBlockHeight` method
Tests and Docs are usually not needed to be added in the changelog (they're dev-related and we're assumed is a given). They can be in the commit thou.

2024-03-15 16:10 UTC, ZER0 commented on example/index.html
> +                // let sync = await wallet.sync();
Why the added comment?

2024-03-15 16:10 UTC, ZER0 commented on example/index.html
> +                // wallet.reset();
Same question.

2024-03-15 16:10 UTC, ZER0 commented on src/graphql.js
> +export async function latestBlockHeight() {
It's confusing why is called differently; it should be called `getNetworkBlockHeight` too.

2024-03-15 16:10 UTC, ZER0 commented on src/graphql.js
> +  return new Promise((r) => r(lastTx.transactions[0].blockHeight ?? 0));
This code makes no sense:
1. You are already in `async` function, you don't need to return a `Promise`. You can just have:
```js
export async function networkBlockHeight() {
  const lastTx = await graphQLRequest(
    `query { transactions(last: 1) { blockHeight }}`,
  );

  return lastTx.transactions[0].blockHeight ?? 0;
}
```

2. You don't even need the `async` function. You can just return the `promise` from the `graphQLRequest`:
```js
export const networkBlockHeight = () => graphQLRequest(
    `query { transactions(last: 1) { blockHeight }}`,
  ).then(tx => tx.transactions[0].blockHeight ?? 0);
```

2024-03-15 16:10 UTC, ZER0 commented on src/mod.js
> +  getNetworkBlockHeight() {
It should be a static method as stated in the issue: it doesn't depends by any instance field. I would create something like:

```js
class Wallet {
  static get networkBlockHeight() {
    return getNetworkBlockHeight()
  }
  …
}
```

If you want to add an instance getter as well for simplicity it's fine, so that it's easily accessible from both `Wallet` class and `Wallet` instance (otherwise they have to use `wallet.constructor.networkBlockHeight`, unless they will requires `Wallet` again), but it should be able to be called without instantiate the wallet. So the end code would looks like:

```js
class Wallet {
  static get networkBlockHeight() {
    return getNetworkBlockHeight()
  }

  get networkBlockHeight() {
    return Wallet.networkBlockHeight
  }
  …
}
```

2024-03-15 16:10 UTC, ZER0 commented on tests/balance_test.js
> +    // sanity check
The term "sanity check" should be avoided nowadays in IT development, for the same reason as "black list", "master/slave" etc, although it's still commonly used.

Alternatives, based on the context, might be:

- coherence check
- consistency check
- confidence check
- validity check
- quick check

Although here you're not doing any "sanity check", you're just performing a normal assertion / expectation.

2024-03-15 16:10 UTC, ZER0 commented on tests/balance_test.js
> +  sanitizeOps: false,
Why you need those? Are you using `indexedDb` or do you have other errors?

2024-03-17 22:23 UTC, herr-seppia commented on src/graphql.js
> +  graphQLRequest(`query { transactions(last: 1) { blockHeight }}`).then(
This query should be avoided because `last` is totally not performant

Pls query for block with height: -1 if you want to know the last network block height

2024-03-18 11:46 UTC, ZER0 requested changes
Minor nits, but ensure to address the comment from Seppia since it's performance related.

2024-03-18 11:46 UTC, ZER0 commented on src/graphql.js
> +export const networkBlockHeight = () =>
You inverted the naming convention from my review's comment:

The *function* should be called `getNetworkBlockHeight`, the *accessor* should be called `networkBlockHeight`.

See: https://github.com/dusk-network/dusk-wallet-js/pull/79#discussion_r1526507406 

You could remove the `get` from the *function* tbh, but since the naming convention of the accessor it's easier to name as indicated.

2024-03-18 11:46 UTC, ZER0 commented on src/mod.js
> +import { networkBlockHeight } from "./graphql.js";
See my previous comment.

2024-03-18 11:46 UTC, ZER0 commented on src/mod.js
> +  }
That should have been:
```js
static get networkBlockheight() {
  return getNetworkBlockHeight();
}
```

Before landing, double check with @nortonandreev and @ascartabelli if they would like to have an `instance` mirror method, or a static class method will suffice.

2024-03-18 11:49 UTC, ascartabelli commented on src/mod.js
> +  }
> Before landing, double check with @nortonandreev and @ascartabelli if they would like to have an `instance` mirror method, or a static class method will suffice.

Not necessary as the instance is not exposed to the UI code anyway as everything is done through a service. 

(cc @Daksh14 )

2024-03-19 12:43 UTC, nortonandreev commented on src/mod.js
> +  }
> > Before landing, double check with @nortonandreev and @ascartabelli if they would like to have an `instance` mirror method, or a static class method will suffice.
> 
> 
> 
> Not necessary as the instance is not exposed to the UI code anyway as everything is done through a service. 
> 
> 
> 
> (cc @Daksh14 )
> 
> 

Not just that, but the Wallet won't be initialised yet at the point where we display the current block height while creating the wallet.

The initialisation happens after the last step in the Wizard, while the step to show the current block height comes before that (obviously, as it's a step in the wizard, as part of the Create Wallet flow).

2024-03-19 14:53 UTC, Daksh14 commented on src/mod.js
> +  }
@nortonandreev @ascartabelli Use `Wallet.networkBlockHeight(): Promise`

2024-03-19 18:33 UTC, ZER0 approved these changes
LGTM

2024-03-19 18:37 UTC, merged