Implement sync scenarios
dusk-network/dusk-wallet-js pull request #94
Opened 2024-05-15 23:39 UTC by Daksh14

Closes #93

2024-06-10 11:20 UTC, ZER0 requested changes
Looks good but there are few things to address.

2024-06-10 11:20 UTC, ZER0 commented on src/node.js
> +class ClearCacheBeforeSync extends Error {
1. If you want to have `dusk-wallet-js` to have it's own errors (this was something to do later on, but it's fine to do it now) it might be better to have a module that defines all the errors the lib defines (such as we do for Rust)
2. To be idiomatic with JS, errors should have the suffix `Error`. For example: `SyntaxError`, `ReferenceError`, etc.
3. This error is way to specific. For the moment I would just create a generic `SyncError` and if we would need in the future specialization we could extends from there.
4. Especially due to the sync and cache decoupling, it's better if the error currently is a bit more generic, so focus on the actual sync instead of the cache – at least for the cache. We throw away less code. We will adjust better once the decoupling is done.

2024-06-10 11:20 UTC, ZER0 commented on src/node.js
> +  }
1. No need to declare a variable, since you can pass the string directly to `super` that will call the constructor of `Error`, that automatically sets the `message`. So the code above it's exactly the same as having:
```js
constructor() {
  super("Clear cache before syncing")
```
2. It's good practice to set the attribute `name` since otherwise it will keep the one from the original class:
```js
class FooError extends Error {
  constructor() {
    super("A Foo Error")
  }
}

let a = new FooError();
let b = new SyntaxError();

console.log(a.name) // "Error"
console.log(b.name) // "SyntaxError"
```

So the proper code for the constructor when we create custom error is:

```js
class FooError extends Error {
  constructor() {
    super("A Foo Error");
    this.name = this.constructor.name;
  }
}

let a = new FooError();
console.log(a.name) // "FooError"
```

2024-06-10 11:20 UTC, ZER0 commented on src/node.js
> +        throw new ClearCacheBeforeSync();
So, as previously mentioned, my suggestion would be here have something like:
```js
throw new SyncError(`Cannot sync from block height ${from} with an existing cache`);
```

Therefore, the error's class would looks like:

```js
class SyncError extends Error {
  constructor(message) {
    super(message);
    this.name = this.constructor.name;
  }
}
```

2024-06-10 11:20 UTC, ZER0 commented on src/node.js
> +        // point 6 throw error if position exists and we're trying to sync from 0
What all these comments about `points` are referring to? If it's related to any of the issue's description, maybe it's worth to having there too otherwise it's not clear at all.

2024-06-10 20:25 UTC, Daksh14 commented on src/node.js
> +        // point 6 throw error if position exists and we're trying to sync from 0
https://github.com/dusk-network/dusk-wallet-js/issues/93#issuecomment-2107632916

2024-06-11 05:54 UTC, ZER0 requested changes
We need to include the legend of the sync scenarios in a way or in another, otherwise the code comments make no sense.

2024-06-11 05:54 UTC, ZER0 commented on src/node.js
> +        // point 6 throw error if position exists and we're trying to sync from 0
My suggestion is, since we're decoupling the sync from cache and this behavior is going to change, is not spending too much time. However, you can't add "points" in comments without actually have the list of what you're referring to.
My suggestion is just mentioned the permalink of the above comment in the `sync` method documentation, and mention that the behavior of the sync is described there, and when in the code you're referring to "points" (I would change them into "scenarios", so that would be _"scenario 6 throws an error if position exists"_ etc.

This is the minimum thing we can do, otherwise in an ideal world the scenario would be included into documentation directly. But as said, the logic is going to be slightly change, so we can discuss that after the decoupling. But a "legend" needs to be included nevertheless.

2024-06-26 09:53 UTC, ZER0 approved these changes
LGTM

2024-06-28 10:51 UTC, merged